#!/bin/bash
#--------------------------------------------------
inputf=''
outputf=''
quality=20
#--------------------------------------------------

usage="`basename $0` OPTIONS [INPUT_FILENAME] [OUTPUT_FILENAME(.mp4)]
  OPTIONS:
    [-q QUALITY]  : quality (default: $quality)
    [--] : finish to parse option
    [-help] : show help"
#--------------------------------------------------

while true; do
  case "$1" in
    -i)  inputf=$2; shift 2 ;;
    -o)  outputf=$2; shift 2 ;;
    -q)  quality=$2; shift 2 ;;
    -help|--help) echo "usage: $usage"; exit 0 ;;
    --|'') shift; break ;;
    *)
        if [ -z "$inputf" ];then
          inputf=$1
          shift 1
        elif [ -z "$outputf" ];then
          outputf=$1
          shift 1
        else
          echo "unexpected option '$1'" >&2
          echo ''
          echo "usage: $usage"
          exit 1
        fi
        ;;
  esac
done

if [ -z "$inputf" ];then
  echo "error! specify the INPUT_FILENAME"
  echo ''
  echo "usage: $usage"
  exit 1
fi

if [ -z "$outputf" ];then
  echo "error! specify the OUTPUT_FILENAME"
  echo ''
  echo "usage: $usage"
  exit 1
fi

#--------------------------------------------------

tmpfile=/tmp/conv-video2-$$-$(basename $inputf).mp4
HandBrakeCLI -i $inputf -o $tmpfile -e x264 -q 20 -O
#Copy the metadata because HandBrakeCLI does not copy it
avconv -i $inputf -i $tmpfile -map 1 -map_metadata 0 -c copy $outputf
rm -v $tmpfile
echo "Done: $inputf --> $outputf"

