#!/bin/bash
# copy url (full-path) to clipboard; symbolic link is resolved
usage='cpa PATH'

# if [ -h $1 ];then
#   f=$(readlink $1)
# else
#   f=$1
# fi
# if [ "$(echo $f|head -c1)" == "/" ];then
#   p=$f
# else
#   p=$(pwd -P)/$f
# fi
if [ -e "$1" ];then
  f=$(realpath $1)
else
  f=$1
fi
if [ "$(echo $f|head -c1)" == "/" ];then
  p=$f
else
  p=$(realpath .)/$f
fi
echo "Copying $p to clipboard"
echo -n $p | $HOME/bin/python/xc

#echo -n `pwd`/$1 | xclip -i -selection clipboard
