#! /bin/bash
infile=""
outfile=""
#--------------------------------------------------

usage="`basename $0` OPTIONS INPUT_FILE [OUTPUT_FILE]
Convert INPUT_FILE (EPS) to OUTPUT_FILE (EPS) of grayscale.
  OPTIONS:
    [--]       : following options are directly used in convert
    [-help]    : show help
"
#--------------------------------------------------

while true; do
  case "$1" in
    -help|--help) echo "usage: $usage"; exit 0 ;;
    --|'') shift; break ;;
    -*) echo "invalid option: $1"; echo ""; echo "usage: $usage"; exit 0 ;;
    *)
      if [ "$infile" == "" ];then
        infile="$1"
      else
        outfile="$1"
      fi
      shift 1
      ;;
  esac
done

if [ "$infile" == "" ];then
  echo "no input file"
  echo ""
  echo "usage: $usage"
  exit 1
fi
if [ "$outfile" == "" ];then
  outfile=$(basename "$infile")
  if [ "$outfile" == "$infile" ];then
    echo "specify output file"
    echo ""
    echo "usage: $usage"
    exit 1
  fi
fi

#--------------------------------------------------

tmp=/tmp/__tmp$$_eps2gray.eps
eps2eps $infile $tmp
pscol -gray $tmp $outfile
rm $tmp

