#!/bin/bash
ts=0
if [ $1 == "test" ]; then
  ts=1
fi
i=0
for f in `find .`; do
  if [ -d $f ]; then
    continue
  fi
  ext=`basename $f | sed 's/\(.\+\)\(\..\{1,10\}$\)/\2/'`
  if [ $ext == `basename $f` ]; then
    ext=""
  fi
  if [ $ts == 0 ]; then
    mv  $f  ${f/`basename $f`/x$i${ext}}
  else
    echo "$f  -->  ${f/`basename $f`/x$i${ext}}"
  fi
  i=$((i+1))
done

