#! /bin/bash -x
usage="usage: ps2svg hoe1.ps [hoe2.ps [...]]"

if [ $# -lt 1 ];  then
  echo "error"
  echo ${usage}
  exit 1
fi

for fname in $@; do
  svgname="`echo ${fname} | sed 's/\(.\+\)\(\..\{1,10\}$\)/\1/'`"
  svgname="`echo ${svgname} | sed 's/\([^\/]*\/\)*\([^\/]*\)$/\2/g'`"
  epsname="${svgname}.eps"
  pbmname="${svgname}.pbm"
  svgname="${svgname}.svg"
  # gs を一端epsに変換
  # gs -q -sDEVICE=epswrite -sOutputFile=${epsname} -r9600 -dNOPAUSE -dBATCH -dSAFER -dEPSCrop ${fname}
  # pstoedit -f plot-svg -dt -ssp ${epsname} ${svgname}
  # rm ${epsname}
  # gs をラスタにして，ベクタ化
  gs -q -sDEVICE=pbm -sOutputFile=${pbmname} -r2400 -dNOPAUSE -dBATCH -dSAFER -dEPSCrop ${fname}
  potrace -o ${svgname} -s ${pbmname}
  rm ${pbmname}
done
