#!/bin/bash

width=297mm
height=210mm
xinit=0
yinit=0
xstep=0
ystep=0
inverse=0

files=

while true; do
  case "$1" in
    -w)  width="$2"; shift 2 ;;
    -h)  height="$2"; shift 2 ;;
    -xi) xinit="$2"; shift 2 ;;
    -yi) yinit="$2"; shift 2 ;;
    -xs) xstep="$2"; shift 2 ;;
    -ys) ystep="$2"; shift 2 ;;
    -i)  inverse=1; shift 1 ;;
    '') shift; break ;;
    *)
      files="$files `pwd`/$1"
      shift;;
  esac
done

echo "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>

<svg
   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"
   xmlns:cc=\"http://creativecommons.org/ns#\"
   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"
   xmlns:svg=\"http://www.w3.org/2000/svg\"
   xmlns=\"http://www.w3.org/2000/svg\"
   xmlns:xlink=\"http://www.w3.org/1999/xlink\"
   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"
   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"
   width=\"$width\"
   height=\"$height\"
   id=\"svg2\"
   version=\"1.1\"
   sodipodi:docname=\"Image Array\">
  <defs
     id=\"defs4\" />
  <sodipodi:namedview
     id=\"base\"
     pagecolor=\"#ffffff\"
     bordercolor=\"#666666\"
     borderopacity=\"1.0\"     />

  <g
     inkscape:label=\"Layer 1\"
     inkscape:groupmode=\"layer\"
     id=\"layer1\">
"

if [ $inverse -eq 1 ];then
  files2="$files"
  files=
  for f in $files2;do
    files="$f $files"
  done
fi

x=$xinit
y=$yinit
for f in $files;do
  echo "<image
       x=\"$x\"
       y=\"$y\"
       id=\"$(basename $f)\"
       xlink:href=\"file://$f\"
       height=\"$(identify -format "%h" $f)\"
       width=\"$(identify -format "%w" $f)\" />"
  x=$(($x+$xstep))
  y=$(($y+$ystep))
done

echo "  </g>
</svg>"
