<?xml version="1.0" ?>
<!-- Receiving container of ode_grpour_sim -->
<robot name="container1" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="Thickness"    default="0.005" />
  <xacro:arg name="SizeX"        default="0.3" />
  <xacro:arg name="SizeY"        default="0.4" />
  <xacro:arg name="SizeZ"        default="0.2" />

  <xacro:macro name="box_geom" params="xyz rpy size">
    <origin xyz="${xyz}" rpy="${rpy}"/>
    <geometry><box size="${size}"/></geometry>
  </xacro:macro>

  <xacro:macro name="add_box" params="xyz rpy size">
    <visual>
      <xacro:box_geom xyz="${xyz}" rpy="${rpy}" size="${size}"/>
      <material name="container_material"/>
    </visual>
    <collision>
      <xacro:box_geom xyz="${xyz}" rpy="${rpy}" size="${size}"/>
    </collision>
  </xacro:macro>

  <material name="container_material">
    <color rgba="1 1 0.5 1"/>
  </material>

  <link name="base_link">
    <contact>
      <rolling_friction value="0.1"/>
      <spinning_friction value="0.1"/>
    </contact>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.7"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>

    <xacro:property name="sizex"  value="$(arg SizeX)" />
    <xacro:property name="sizey"  value="$(arg SizeY)" />
    <xacro:property name="sizez"  value="$(arg SizeZ)" />
    <xacro:property name="thickness" value="$(arg Thickness)" />
    <xacro:property name="bottom_z" value="0.0" />
    <xacro:property name="M_SQRT2" value="${sqrt(2.0)}" />

    <!--Main body of the container:-->
    <xacro:add_box rpy="0 0 0" xyz="${0.0} ${0.0} ${0.5*thickness+bottom_z}"
                   size="${sizex-2.0*thickness} ${sizey-2.0*thickness} ${thickness}" />
    <xacro:add_box rpy="0 0 0" xyz="${0.5*sizex-0.5*thickness} ${0.0} ${0.5*sizez+bottom_z}"
                   size="${thickness} ${sizey} ${sizez}" />
    <xacro:add_box rpy="0 0 0" xyz="${-0.5*sizex+0.5*thickness} ${0.0} ${0.5*sizez+bottom_z}"
                   size="${thickness} ${sizey} ${sizez}" />
    <xacro:add_box rpy="0 0 0" xyz="${0.0} ${0.5*sizey-0.5*thickness} ${0.5*sizez+bottom_z}"
                   size="${sizex-2.0*thickness} ${thickness} ${sizez}" />
    <xacro:add_box rpy="0 0 0" xyz="${0.0} ${-0.5*sizey+0.5*thickness} ${0.5*sizez+bottom_z}"
                   size="${sizex-2.0*thickness} ${thickness} ${sizez}" />

  </link>
</robot>
