#!/usr/bin/python3
import sys,subprocess
text=sys.stdin.read().rstrip()

try:
  p = subprocess.Popen(['xclip', '-i', '-selection', 'clipboard'], stdin=subprocess.PIPE, universal_newlines=True)
  p.stdin.write(text)
  p.stdin.close()
  retcode = p.wait()
except:
  pass
