# GENERATED BY GEMINI AND NO CHECK YET

from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch.substitutions import Command, FindExecutable, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch_ros.parameter_descriptions import ParameterValue

def generate_launch_description():
    # パス設定
    pkg_share = FindPackageShare("ros2_mock_gp7")

    # 1. Xacroを展開してURDFにする
    # ParameterValue でラップして、ただの文字列であることを明示します
    robot_description_content = ParameterValue(
        Command(
            [
                PathJoinSubstitution([FindExecutable(name="xacro")]),
                " ",
                PathJoinSubstitution([pkg_share, "urdf", "mock_gp7.urdf.xacro"]),
            ]
        ),
        value_type=str
    )

    robot_description = {"robot_description": robot_description_content}

    # 2. コントローラ設定ファイルのパス
    robot_controllers = PathJoinSubstitution(
        [pkg_share, "config", "controllers.yaml"]
    )

    # 3. ノード定義
    # Controller Manager (ros2_controlの本体)
    control_node = Node(
        package="controller_manager",
        executable="ros2_control_node",
        parameters=[robot_description, robot_controllers],
        output="both",
    )

    # Robot State Publisher (TF配信)
    rsp_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="both",
        parameters=[robot_description],
    )

    # RViz2
    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="log",
        # 設定ファイルがあれば指定可能
        # arguments=["-d", PathJoinSubstitution([pkg_share, "rviz", "view.rviz"])]
    )

    # 4. コントローラのスポーン (起動)
    joint_state_broadcaster_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster", "--controller-manager", "/controller_manager"],
    )

    robot_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_trajectory_controller", "--controller-manager", "/controller_manager"],
    )

    # 起動順序の制御 (Managerが立ち上がってからSpawnerを呼ぶ)
    delay_robot_controller_spawner_after_joint_state_broadcaster_spawner = RegisterEventHandler(
        event_handler=OnProcessExit(
            target_action=joint_state_broadcaster_spawner,
            on_exit=[robot_controller_spawner],
        )
    )

    return LaunchDescription([
        control_node,
        rsp_node,
        rviz_node,
        joint_state_broadcaster_spawner,
        delay_robot_controller_spawner_after_joint_state_broadcaster_spawner,
    ])
